mergeable:
  pull_requests:
    label:
      must_include:
        regex: `.+`
      must_exclude:
        regex: `^wip$`
    title:
      must_exclude:
        regex: `^WIP`
    description:
      must_include:
        regex: `^.{10,}`
        message: 'The description must not be empty (at least 10 characters)!'
    stale:
      days: 10
      message: 'There has not been any activity in the past 10 days. Is this still active?'
  issues:
    label:
      must_include:
        regex: `.+`
    stale:
      days: 30
      message: 'There has not been any activity in the past month. Is there anything to follow-up?'
    description:
      must_include:
        regex: `^.{10,}`
        message: 'The description must not be empty (at least 10 characters)!'
