mergeable:
  pull_requests:
    label:
      must_include:
        regex: ".+"
        message: "The pull-request is not categorized using any label."
      must_exclude:
        regex: "^wip$"
        message: "The pull-request is labelled as work in progress (WIP)."
    title:
      must_exclude:
        regex: "^WIP"
        message: "The pull-request is titled as work in progress (WIP:)."
    description:
      must_include:
        regex: "^.{10,}"
        message: 'The description must not be empty (at least 10 characters)!'
    stale:
      days: 10
      message: 'There has not been any activity in the past 10 days. Is this still active?'
  issues:
    label:
      must_include:
        regex: ".+"
        message: "The issue is not categorized using any label."
    stale:
      days: 30
      message: 'There has not been any activity in the past month. Is there anything to follow-up?'
    description:
      must_include:
        regex: "^.{10,}"
        message: 'The description must not be empty (at least 10 characters)!'
