.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. unite_qt test_unite_qt
clean: FORCE
	$(MAKE) -C .. unite_qt_clean test_unite_qt_clean
check: FORCE
	$(MAKE) -C .. test_unite_qt_check
unite-qt unite-qt.exe: FORCE
	 $(MAKE) -C .. unite_qt
