#ifndef UNIT_E_STAKING_VALIDATION_ERROR_H
#define UNIT_E_STAKING_VALIDATION_ERROR_H

#include <better-enums/enum.h>

namespace staking {

// clang-format off
BETTER_ENUM(
    BlockValidationError,
    std::uint8_t,
    BLOCK_SIGNATURE_VERIFICATION_FAILED,
    COINBASE_TRANSACTION_AT_POSITION_OTHER_THAN_FIRST,
    COINBASE_TRANSACTION_WITHOUT_OUTPUT,
    DUPLICATE_STAKE,
    DUPLICATE_TRANSACTIONS_IN_MERKLE_TREE,
    DUPLICATE_TRANSACTIONS_IN_WITNESS_MERKLE_TREE,
    FIRST_TRANSACTION_NOT_A_COINBASE_TRANSACTION,
    INVALID_BLOCK_HEIGHT,
    INVALID_BLOCK_TIME,
    INVALID_BLOCK_PUBLIC_KEY,
    MERKLE_ROOT_MISMATCH,
    NO_BLOCK_HEIGHT,
    NO_COINBASE_TRANSACTION,
    NO_META_INPUT,
    NO_SNAPSHOT_HASH,
    NO_STAKING_INPUT,
    NO_TRANSACTIONS,
    PREVIOUS_BLOCK_NOT_PART_OF_ACTIVE_CHAIN,
    STAKE_IMMATURE,
    STAKE_NOT_ELIGIBLE,
    STAKE_NOT_FOUND,
    WITNESS_MERKLE_ROOT_MISMATCH
)
// clang-format on

std::string GetRejectionMessageFor(BlockValidationError);

}

#endif //UNIT_E_VALIDATION_ERROR_H
